version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
    configs:
     - source: es
       target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
    configs:
     - source: ls
       target: /usr/share/logstash/config/logstash.yml
     - source: ls-pipe
       target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
    configs:
     - source: kb
       target: /usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    healthcheck: 
        test: ["CMD-SHELL", "curl --silent --fail localhost:5601 || exit 1"]
        interval: 60s 
        timeout: 10s 
        retries: 40

  metricbeat:
    # this needs to be root for you to monitor host docker socket
    user: root
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    configs:
     - source: mb
       target: /usr/share/metricbeat/metricbeat.yml
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
      - /proc:/hostfs/proc
      - /:/hostfs
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - elk
    depends_on:
      - logstash
      - kibana

  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    networks:
      - elk
    configs:
     - source: fb
       target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat_data:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    depends_on: 
      - logstash
      - kibana
    
volumes:
  filebeat_data:

configs:
    es:
        file: ./elasticsearch/config/elasticsearch.yml
    kb:
        file: ./kibana/config/kibana.yml
    ls:
        file: ./logstash/config/logstash.yml
    ls-pipe:
        file: ./logstash/pipeline/logstash.conf
    mb:
        file: ./metricbeat/metricbeat.docker.yml
    fb:
        file: ./filebeat/filebeat.yml

networks:
  elk: